name: Build website

on: [push]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Deploy
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.58.3
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        TOKEN: ${{ secrets.TOKEN }}
